<?php
// $Id$

/**
 * @file
 *   LABjs module
 */

define('LABJS_EXCLUDE', '// LABjs exclusion');

/**
 * Implements hook_js_alter().
 */
function labjs_js_alter(&$javascript) {
  $scripts = array();
  $files = array();
  $preprocess_js = (variable_get('preprocess_js', FALSE) && (!defined('MAINTENANCE_MODE') || MAINTENANCE_MODE != 'update'));
  // The index counter is used to keep aggregated and non-aggregated files in
  // order by weight.
  $index = 1;

  // Sorts the scripts into correct order
  // Drupal assigns different weight for each scripts, thus we can't determine
  // if two scripts can be executed in parallel. However, they are all loaded in
  // parallel.
  uasort($javascript, 'drupal_sort_css_js');
  foreach ($javascript as $key => $item) {
    if (empty($item['inline'])) {
      if ($item['type'] == 'file' || $item['type'] == 'external') {
        if ($item['type'] == 'external' || !$item['preprocess'] || !$preprocess_js) {
          $src = $item['type'] == 'external' ? $item['data'] : file_create_url($item['data']);
          $scripts[$index++] = "\"$src\"";
        }
        else {
          $filekey = 'aggregate_' . $item['group'] . '_' . $item['every_page'] . '_' . $index;
          $files[$filekey][$item['data']] = $item;
        }
        unset($javascript[$key]);
      }
    }
    elseif ($item['type'] == 'inline') {
      $javascript[$key]['data'] = LABJS_EXCLUDE . "\n" . $javascript[$key]['data'];
    }
  }

  // Aggregates any remaining JS files
  if ($preprocess_js && count($files) > 0) {
    foreach ($files as $key => $file_set) {
      $uri = drupal_build_js_cache($file_set);
      // Only include the file if was written successfully. Errors are logged
      // using watchdog.
      if ($uri) {
        $scripts[$key] = "\"" . file_create_url($uri) . "\"";
      }
    }
  }

  // Adds the JS function call
  $javascript['labjs'] = array(
    'scope' => 'header',
    'type' => 'inline',
    'data' => LABJS_EXCLUDE . "\nvar _lab = \$LAB\n.setOptions({AlwaysPreserveOrder:true})\n.script(" . implode(")\n.script(", $scripts) . ");",
    'defer' => FALSE,
    'group' => JS_LIBRARY,
    'weight' => -50,
  );
}

/**
 * Implements hook_preprocess_html_tag().
 *
 * Inline JavaScript blocks must be executed in order. In the blocking script load,
 * this is the default behavior. With LAB, we must wrap them in wait() to preserve
 * this behavior
 */
function labjs_preprocess_html_tag(&$variables) {
  if ($variables['element']['#tag'] == 'script' && !empty($variables['element']['#value']) && strpos($variables['element']['#value'], LABJS_EXCLUDE) !== 0) {
    $variables['element']['#value'] = "_lab.wait(function() {\n" . $variables['element']['#value'] . "\n});";
  }
}

/**
 * Implements hook_preprocess_page().
 */
function labjs_preprocess_page(&$variables) {
  $javascript = preg_replace_callback('#<script .+?</script>#s', '_labjs_rewrite_js', $variables['scripts']);
  $scripts = _labjs_rewrite_js();
  $variables['scripts'] = '<script type="text/javascript" src="' . base_path() . 'sites/all/libraries/labjs/LAB.min.js"></script>' .
    '<script type="text/javascript">' . "\nvar _lab = \$LAB\n.setOptions({AlwaysPreserveOrder:true})\n.script(" . implode(")\n.script(", $scripts) . ");\n</script>" .
    $javascript;
}

/**
 * Rewrites all <script> tag to use LABjs.
 */
function _labjs_rewrite_js($matches = NULL) {
  // We store all parsed scripts in the $scripts array.
  // When call without parameter, we return this array.
  static $scripts = array();
  if (! $matches) {
    return $scripts;
  }
  else {
    // If this is an inline script, we remove and add the src to $scripts array.
    // If not, we try to wrap it with $LAB.wait()
    if (preg_match('#type="text/javascript" src="(.+?)"#', $matches[0], $match)) {
      $scripts[] = "\"{$match[1]}\"";
      return '';
    }
    else {
      return (strpos($matches[0], LABJS_EXCLUDE) !== FALSE) ? $matches[0] : str_replace(
        array("<!--//--><![CDATA[//><!--", "//--><!]]>"), 
        array("<!--//--><![CDATA[//><!--\n_lab.wait(function() {", "});\n//--><!]]>"),
        $matches[0]);
    }
  }
}